version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./storage:/app/storage
    environment:
      - DB__URL=sqlite+aiosqlite:////app/dev.db
    restart: unless-stopped
