version: '3.8'

services:
  amras:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: amras_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
      - ./cache:/app/cache
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
    # command: "uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload"
