"""Add manga ingestion tables

Revision ID: 13bc1c478374
Revises: 3745f408bd3b
Create Date: 2026-07-04 19:48:13.505591

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '13bc1c478374'
down_revision: Union[str, Sequence[str], None] = '3745f408bd3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('bandwidth', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_jobs_provider'), 'download_jobs', ['provider'], unique=False)
    op.create_index(op.f('ix_download_jobs_status'), 'download_jobs', ['status'], unique=False)
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('current_file', sa.String(length=1024), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_status'), 'import_jobs', ['status'], unique=False)
    op.create_table('mangas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mangas_hash'), 'mangas', ['hash'], unique=False)
    op.create_index(op.f('ix_mangas_slug'), 'mangas', ['slug'], unique=True)
    op.create_index(op.f('ix_mangas_title'), 'mangas', ['title'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('imported', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['mangas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_chapter_number'), 'chapters', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_chapters_manga_id'), 'chapters', ['manga_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=1024), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_chapter_id'), 'pages', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_pages_image_hash'), 'pages', ['image_hash'], unique=False)
    op.create_index(op.f('ix_pages_page_number'), 'pages', ['page_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_page_number'), table_name='pages')
    op.drop_index(op.f('ix_pages_image_hash'), table_name='pages')
    op.drop_index(op.f('ix_pages_chapter_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_chapters_manga_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_chapter_number'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_mangas_title'), table_name='mangas')
    op.drop_index(op.f('ix_mangas_slug'), table_name='mangas')
    op.drop_index(op.f('ix_mangas_hash'), table_name='mangas')
    op.drop_table('mangas')
    op.drop_index(op.f('ix_import_jobs_status'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_download_jobs_status'), table_name='download_jobs')
    op.drop_index(op.f('ix_download_jobs_provider'), table_name='download_jobs')
    op.drop_table('download_jobs')
    # ### end Alembic commands ###
