"""Add subtitles models

Revision ID: 367618f06535
Revises: e8c68d1fa1bc
Create Date: 2026-07-08 08:45:59.925119

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "367618f06535"
down_revision: Union[str, Sequence[str], None] = "e8c68d1fa1bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "animation_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_animation_profiles_name"), "animation_profiles", ["name"], unique=True)
    op.create_table(
        "camera_paths",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("start_zoom", sa.Float(), nullable=False),
        sa.Column("end_zoom", sa.Float(), nullable=False),
        sa.Column("start_x", sa.Float(), nullable=False),
        sa.Column("start_y", sa.Float(), nullable=False),
        sa.Column("end_x", sa.Float(), nullable=False),
        sa.Column("end_y", sa.Float(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "encoding_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("resolution", sa.String(length=50), nullable=False),
        sa.Column("fps", sa.Integer(), nullable=False),
        sa.Column("video_codec", sa.String(length=50), nullable=False),
        sa.Column("audio_codec", sa.String(length=50), nullable=False),
        sa.Column("video_bitrate", sa.String(length=50), nullable=False),
        sa.Column("audio_bitrate", sa.String(length=50), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_encoding_profiles_name"), "encoding_profiles", ["name"], unique=True)
    op.create_table(
        "scene_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("emotion", sa.String(length=100), nullable=True),
        sa.Column("intensity", sa.Float(), nullable=False),
        sa.Column("visual_complexity", sa.Float(), nullable=False),
        sa.Column("dialogue_density", sa.Float(), nullable=False),
        sa.Column("is_battle", sa.Boolean(), nullable=False),
        sa.Column("is_flashback", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "timelines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_timelines_project_id"), "timelines", ["project_id"], unique=False)
    op.create_index(op.f("ix_timelines_status"), "timelines", ["status"], unique=False)
    op.create_table(
        "render_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("timeline_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["encoding_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["timeline_id"],
            ["timelines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_render_jobs_profile_id"), "render_jobs", ["profile_id"], unique=False)
    op.create_index(op.f("ix_render_jobs_project_id"), "render_jobs", ["project_id"], unique=False)
    op.create_index(op.f("ix_render_jobs_status"), "render_jobs", ["status"], unique=False)
    op.create_index(op.f("ix_render_jobs_timeline_id"), "render_jobs", ["timeline_id"], unique=False)
    op.create_table(
        "encoded_videos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("format", sa.String(length=50), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=255), nullable=True),
        sa.Column("metadata_info", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["render_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_encoded_videos_job_id"), "encoded_videos", ["job_id"], unique=False)
    op.create_table(
        "output_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["render_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_output_files_job_id"), "output_files", ["job_id"], unique=False)
    op.create_table(
        "render_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("total_time_ms", sa.Integer(), nullable=False),
        sa.Column("average_fps", sa.Float(), nullable=False),
        sa.Column("peak_ram_mb", sa.Float(), nullable=False),
        sa.Column("peak_gpu_mb", sa.Float(), nullable=False),
        sa.Column("dropped_frames", sa.Integer(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["render_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_render_reports_job_id"), "render_reports", ["job_id"], unique=True)
    op.create_table(
        "render_statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("cpu_usage", sa.Float(), nullable=False),
        sa.Column("gpu_usage", sa.Float(), nullable=False),
        sa.Column("ram_usage_mb", sa.Float(), nullable=False),
        sa.Column("current_fps", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["render_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_render_statistics_job_id"), "render_statistics", ["job_id"], unique=False)
    op.create_table(
        "timeline_scenes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timeline_id", sa.Integer(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("start_time_ms", sa.Integer(), nullable=False),
        sa.Column("end_time_ms", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=True),
        sa.Column("transition_id", sa.Integer(), nullable=True),
        sa.Column("metadata_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["metadata_id"],
            ["scene_metadata.id"],
        ),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["pages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["timeline_id"],
            ["timelines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transition_id"],
            ["transitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_timeline_scenes_page_id"), "timeline_scenes", ["page_id"], unique=False)
    op.create_index(op.f("ix_timeline_scenes_timeline_id"), "timeline_scenes", ["timeline_id"], unique=False)
    op.create_table(
        "render_scenes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("scene_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("output_path", sa.String(length=1024), nullable=True),
        sa.Column("render_time_ms", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["render_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["timeline_scenes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_render_scenes_job_id"), "render_scenes", ["job_id"], unique=False)
    op.create_index(op.f("ix_render_scenes_scene_id"), "render_scenes", ["scene_id"], unique=False)
    op.create_index(op.f("ix_render_scenes_status"), "render_scenes", ["status"], unique=False)
    op.create_table(
        "timeline_panels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scene_id", sa.Integer(), nullable=False),
        sa.Column("panel_id", sa.Integer(), nullable=True),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("start_time_ms", sa.Integer(), nullable=False),
        sa.Column("end_time_ms", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("importance_score", sa.Float(), nullable=False),
        sa.Column("camera_path_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["camera_path_id"],
            ["camera_paths.id"],
        ),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["timeline_scenes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_timeline_panels_panel_id"), "timeline_panels", ["panel_id"], unique=False)
    op.create_index(op.f("ix_timeline_panels_scene_id"), "timeline_panels", ["scene_id"], unique=False)
    op.create_table(
        "synchronizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scene_id", sa.Integer(), nullable=False),
        sa.Column("audio_segment_id", sa.Integer(), nullable=True),
        sa.Column("narration_id", sa.Integer(), nullable=True),
        sa.Column("start_time_ms", sa.Integer(), nullable=False),
        sa.Column("end_time_ms", sa.Integer(), nullable=False),
        sa.Column("sync_accuracy", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["audio_segment_id"],
            ["audio_segments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["narration_id"],
            ["narration.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["timeline_scenes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_synchronizations_audio_segment_id"), "synchronizations", ["audio_segment_id"], unique=False
    )
    op.create_index(op.f("ix_synchronizations_narration_id"), "synchronizations", ["narration_id"], unique=False)
    op.create_index(op.f("ix_synchronizations_scene_id"), "synchronizations", ["scene_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_synchronizations_scene_id"), table_name="synchronizations")
    op.drop_index(op.f("ix_synchronizations_narration_id"), table_name="synchronizations")
    op.drop_index(op.f("ix_synchronizations_audio_segment_id"), table_name="synchronizations")
    op.drop_table("synchronizations")
    op.drop_index(op.f("ix_timeline_panels_scene_id"), table_name="timeline_panels")
    op.drop_index(op.f("ix_timeline_panels_panel_id"), table_name="timeline_panels")
    op.drop_table("timeline_panels")
    op.drop_index(op.f("ix_render_scenes_status"), table_name="render_scenes")
    op.drop_index(op.f("ix_render_scenes_scene_id"), table_name="render_scenes")
    op.drop_index(op.f("ix_render_scenes_job_id"), table_name="render_scenes")
    op.drop_table("render_scenes")
    op.drop_index(op.f("ix_timeline_scenes_timeline_id"), table_name="timeline_scenes")
    op.drop_index(op.f("ix_timeline_scenes_page_id"), table_name="timeline_scenes")
    op.drop_table("timeline_scenes")
    op.drop_index(op.f("ix_render_statistics_job_id"), table_name="render_statistics")
    op.drop_table("render_statistics")
    op.drop_index(op.f("ix_render_reports_job_id"), table_name="render_reports")
    op.drop_table("render_reports")
    op.drop_index(op.f("ix_output_files_job_id"), table_name="output_files")
    op.drop_table("output_files")
    op.drop_index(op.f("ix_encoded_videos_job_id"), table_name="encoded_videos")
    op.drop_table("encoded_videos")
    op.drop_index(op.f("ix_render_jobs_timeline_id"), table_name="render_jobs")
    op.drop_index(op.f("ix_render_jobs_status"), table_name="render_jobs")
    op.drop_index(op.f("ix_render_jobs_project_id"), table_name="render_jobs")
    op.drop_index(op.f("ix_render_jobs_profile_id"), table_name="render_jobs")
    op.drop_table("render_jobs")
    op.drop_index(op.f("ix_timelines_status"), table_name="timelines")
    op.drop_index(op.f("ix_timelines_project_id"), table_name="timelines")
    op.drop_table("timelines")
    op.drop_table("transitions")
    op.drop_table("scene_metadata")
    op.drop_index(op.f("ix_encoding_profiles_name"), table_name="encoding_profiles")
    op.drop_table("encoding_profiles")
    op.drop_table("camera_paths")
    op.drop_index(op.f("ix_animation_profiles_name"), table_name="animation_profiles")
    op.drop_table("animation_profiles")
    # ### end Alembic commands ###
