"""Add QA models

Revision ID: bf6d04ac8efd
Revises: 96eb6297dae7
Create Date: 2026-07-09 11:53:34.090412

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf6d04ac8efd"
down_revision: Union[str, Sequence[str], None] = "96eb6297dae7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "qa_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("overall_grade", sa.String(length=10), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_qa_reports_project_id"), "qa_reports", ["project_id"], unique=False)
    op.create_index(op.f("ix_qa_reports_status"), "qa_reports", ["status"], unique=False)
    op.create_table(
        "qa_validation_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("metric_name", sa.String(length=100), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_qa_validation_metrics_metric_name"), "qa_validation_metrics", ["metric_name"], unique=False
    )
    op.create_index(op.f("ix_qa_validation_metrics_project_id"), "qa_validation_metrics", ["project_id"], unique=False)
    op.create_table(
        "qa_approval_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["qa_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_qa_approval_history_project_id"), "qa_approval_history", ["project_id"], unique=False)
    op.create_table(
        "qa_issue_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("agent", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("is_fixed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["qa_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_qa_issue_reports_agent"), "qa_issue_reports", ["agent"], unique=False)
    op.create_index(op.f("ix_qa_issue_reports_report_id"), "qa_issue_reports", ["report_id"], unique=False)
    op.create_index(op.f("ix_qa_issue_reports_severity"), "qa_issue_reports", ["severity"], unique=False)
    op.create_table(
        "qa_performance_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("cpu_usage_avg", sa.Float(), nullable=True),
        sa.Column("gpu_usage_avg", sa.Float(), nullable=True),
        sa.Column("memory_usage_mb", sa.Float(), nullable=True),
        sa.Column("disk_usage_mb", sa.Float(), nullable=True),
        sa.Column("pipeline_duration_seconds", sa.Float(), nullable=True),
        sa.Column("phase_durations", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["qa_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_id"),
    )
    op.create_table(
        "qa_quality_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("story_score", sa.Float(), nullable=False),
        sa.Column("narration_score", sa.Float(), nullable=False),
        sa.Column("voice_score", sa.Float(), nullable=False),
        sa.Column("timeline_score", sa.Float(), nullable=False),
        sa.Column("rendering_score", sa.Float(), nullable=False),
        sa.Column("subtitle_score", sa.Float(), nullable=False),
        sa.Column("performance_score", sa.Float(), nullable=False),
        sa.Column("seo_score", sa.Float(), nullable=False),
        sa.Column("security_score", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["qa_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_id"),
    )
    op.create_table(
        "qa_auto_fix_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("issue_id", sa.Integer(), nullable=False),
        sa.Column("action_taken", sa.Text(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["qa_issue_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_qa_auto_fix_history_issue_id"), "qa_auto_fix_history", ["issue_id"], unique=False)
    op.create_table(
        "qa_manual_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("issue_id", sa.Integer(), nullable=True),
        sa.Column("reviewer_notes", sa.Text(), nullable=True),
        sa.Column("decision", sa.String(length=50), nullable=False),
        sa.Column("resolved_by", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["qa_issue_reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["qa_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_qa_manual_reviews_report_id"), "qa_manual_reviews", ["report_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_qa_manual_reviews_report_id"), table_name="qa_manual_reviews")
    op.drop_table("qa_manual_reviews")
    op.drop_index(op.f("ix_qa_auto_fix_history_issue_id"), table_name="qa_auto_fix_history")
    op.drop_table("qa_auto_fix_history")
    op.drop_table("qa_quality_scores")
    op.drop_table("qa_performance_reports")
    op.drop_index(op.f("ix_qa_issue_reports_severity"), table_name="qa_issue_reports")
    op.drop_index(op.f("ix_qa_issue_reports_report_id"), table_name="qa_issue_reports")
    op.drop_index(op.f("ix_qa_issue_reports_agent"), table_name="qa_issue_reports")
    op.drop_table("qa_issue_reports")
    op.drop_index(op.f("ix_qa_approval_history_project_id"), table_name="qa_approval_history")
    op.drop_table("qa_approval_history")
    op.drop_index(op.f("ix_qa_validation_metrics_project_id"), table_name="qa_validation_metrics")
    op.drop_index(op.f("ix_qa_validation_metrics_metric_name"), table_name="qa_validation_metrics")
    op.drop_table("qa_validation_metrics")
    op.drop_index(op.f("ix_qa_reports_status"), table_name="qa_reports")
    op.drop_index(op.f("ix_qa_reports_project_id"), table_name="qa_reports")
    op.drop_table("qa_reports")
    # ### end Alembic commands ###
