"""add_memory_models

Revision ID: db8b0d5e648e
Revises: 13bc1c478374
Create Date: 2026-07-06 10:45:51.817755

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db8b0d5e648e"
down_revision: Union[str, Sequence[str], None] = "13bc1c478374"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "confidence_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conflict_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("conflict_type", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conflict_reports_entity_id"), "conflict_reports", ["entity_id"], unique=False)
    op.create_table(
        "embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("vector", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_embeddings_entity_id"), "embeddings", ["entity_id"], unique=False)
    op.create_table(
        "knowledge_graph_edges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_node_id", sa.String(length=100), nullable=False),
        sa.Column("target_node_id", sa.String(length=100), nullable=False),
        sa.Column("relationship", sa.String(length=100), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_graph_edges_source_node_id"), "knowledge_graph_edges", ["source_node_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_graph_edges_target_node_id"), "knowledge_graph_edges", ["target_node_id"], unique=False
    )
    op.create_table(
        "knowledge_graph_nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_knowledge_graph_nodes_node_id"), "knowledge_graph_nodes", ["node_id"], unique=True)
    op.create_table(
        "memory_audits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_memory_audits_entity_id"), "memory_audits", ["entity_id"], unique=False)
    op.create_table(
        "memory_store",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("memory_type", sa.String(length=50), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_memory_store_entity_id"), "memory_store", ["entity_id"], unique=True)
    op.create_index(op.f("ix_memory_store_entity_type"), "memory_store", ["entity_type"], unique=False)
    op.create_index(op.f("ix_memory_store_memory_type"), "memory_store", ["memory_type"], unique=False)
    op.create_table(
        "retrieval_indices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("keyword", sa.String(length=255), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_retrieval_indices_entity_id"), "retrieval_indices", ["entity_id"], unique=False)
    op.create_index(op.f("ix_retrieval_indices_keyword"), "retrieval_indices", ["keyword"], unique=False)
    op.create_table(
        "ability_memories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("memory_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("ability_type", sa.String(length=100), nullable=False),
        sa.Column("owner_id", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["memory_id"], ["memory_store.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ability_memories_memory_id"), "ability_memories", ["memory_id"], unique=False)
    op.create_index(op.f("ix_ability_memories_name"), "ability_memories", ["name"], unique=False)
    op.create_index(op.f("ix_ability_memories_owner_id"), "ability_memories", ["owner_id"], unique=False)
    op.create_table(
        "character_memories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("memory_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=True),
        sa.Column("current_status", sa.String(length=100), nullable=True),
        sa.Column("first_appearance_chapter", sa.Integer(), nullable=True),
        sa.Column("last_appearance_chapter", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["memory_id"], ["memory_store.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_character_memories_memory_id"), "character_memories", ["memory_id"], unique=False)
    op.create_index(op.f("ix_character_memories_name"), "character_memories", ["name"], unique=False)
    op.create_table(
        "event_memories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("memory_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column("chapter_id", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["memory_id"], ["memory_store.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_memories_chapter_id"), "event_memories", ["chapter_id"], unique=False)
    op.create_index(op.f("ix_event_memories_memory_id"), "event_memories", ["memory_id"], unique=False)
    op.create_index(op.f("ix_event_memories_name"), "event_memories", ["name"], unique=False)
    op.create_table(
        "memory_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("memory_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["memory_id"], ["memory_store.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_memory_versions_memory_id"), "memory_versions", ["memory_id"], unique=False)
    op.create_table(
        "object_memories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("memory_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("object_type", sa.String(length=100), nullable=False),
        sa.Column("owner_id", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["memory_id"], ["memory_store.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_object_memories_memory_id"), "object_memories", ["memory_id"], unique=False)
    op.create_index(op.f("ix_object_memories_name"), "object_memories", ["name"], unique=False)
    op.create_index(op.f("ix_object_memories_owner_id"), "object_memories", ["owner_id"], unique=False)
    op.create_table(
        "relationship_memories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("memory_id", sa.Integer(), nullable=False),
        sa.Column("source_entity_id", sa.String(length=100), nullable=False),
        sa.Column("target_entity_id", sa.String(length=100), nullable=False),
        sa.Column("relationship_type", sa.String(length=100), nullable=False),
        sa.Column("trust_score", sa.Float(), nullable=True),
        sa.Column("conflict_score", sa.Float(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["memory_id"], ["memory_store.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_relationship_memories_memory_id"), "relationship_memories", ["memory_id"], unique=False)
    op.create_index(
        op.f("ix_relationship_memories_source_entity_id"), "relationship_memories", ["source_entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_relationship_memories_target_entity_id"), "relationship_memories", ["target_entity_id"], unique=False
    )
    op.create_table(
        "world_memories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("memory_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("location_type", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["memory_id"], ["memory_store.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_world_memories_memory_id"), "world_memories", ["memory_id"], unique=False)
    op.create_index(op.f("ix_world_memories_name"), "world_memories", ["name"], unique=False)
    op.create_table(
        "panels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("panel_number", sa.Integer(), nullable=False),
        sa.Column("reading_order", sa.Integer(), nullable=False),
        sa.Column("bounding_box", sa.JSON(), nullable=False),
        sa.Column("scene_type", sa.String(length=100), nullable=True),
        sa.Column("emotion", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_panels_page_id"), "panels", ["page_id"], unique=False)
    op.create_table(
        "vision_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vision_jobs_page_id"), "vision_jobs", ["page_id"], unique=False)
    op.create_index(op.f("ix_vision_jobs_status"), "vision_jobs", ["status"], unique=False)
    op.create_table(
        "actions_detected",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("panel_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["panel_id"], ["panels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_actions_detected_panel_id"), "actions_detected", ["panel_id"], unique=False)
    op.create_table(
        "characters_detected",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("panel_id", sa.Integer(), nullable=False),
        sa.Column("identity_estimate", sa.String(length=255), nullable=True),
        sa.Column("gender", sa.String(length=50), nullable=True),
        sa.Column("age_group", sa.String(length=50), nullable=True),
        sa.Column("clothing", sa.Text(), nullable=True),
        sa.Column("expression", sa.String(length=100), nullable=True),
        sa.Column("pose", sa.String(length=100), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("bounding_box", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["panel_id"], ["panels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_characters_detected_panel_id"), "characters_detected", ["panel_id"], unique=False)
    op.create_table(
        "narration",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("panel_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["panel_id"], ["panels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_narration_panel_id"), "narration", ["panel_id"], unique=False)
    op.create_table(
        "objects_detected",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("panel_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("bounding_box", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["panel_id"], ["panels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_objects_detected_panel_id"), "objects_detected", ["panel_id"], unique=False)
    op.create_table(
        "sound_effects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("panel_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("ignore_for_summary", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["panel_id"], ["panels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sound_effects_panel_id"), "sound_effects", ["panel_id"], unique=False)
    op.create_table(
        "speech_bubbles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("panel_id", sa.Integer(), nullable=False),
        sa.Column("speaker", sa.String(length=255), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=True),
        sa.Column("bubble_type", sa.String(length=50), nullable=False),
        sa.Column("bounding_box", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["panel_id"], ["panels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_speech_bubbles_panel_id"), "speech_bubbles", ["panel_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_speech_bubbles_panel_id"), table_name="speech_bubbles")
    op.drop_table("speech_bubbles")
    op.drop_index(op.f("ix_sound_effects_panel_id"), table_name="sound_effects")
    op.drop_table("sound_effects")
    op.drop_index(op.f("ix_objects_detected_panel_id"), table_name="objects_detected")
    op.drop_table("objects_detected")
    op.drop_index(op.f("ix_narration_panel_id"), table_name="narration")
    op.drop_table("narration")
    op.drop_index(op.f("ix_characters_detected_panel_id"), table_name="characters_detected")
    op.drop_table("characters_detected")
    op.drop_index(op.f("ix_actions_detected_panel_id"), table_name="actions_detected")
    op.drop_table("actions_detected")
    op.drop_index(op.f("ix_vision_jobs_status"), table_name="vision_jobs")
    op.drop_index(op.f("ix_vision_jobs_page_id"), table_name="vision_jobs")
    op.drop_table("vision_jobs")
    op.drop_index(op.f("ix_panels_page_id"), table_name="panels")
    op.drop_table("panels")
    op.drop_index(op.f("ix_world_memories_name"), table_name="world_memories")
    op.drop_index(op.f("ix_world_memories_memory_id"), table_name="world_memories")
    op.drop_table("world_memories")
    op.drop_index(op.f("ix_relationship_memories_target_entity_id"), table_name="relationship_memories")
    op.drop_index(op.f("ix_relationship_memories_source_entity_id"), table_name="relationship_memories")
    op.drop_index(op.f("ix_relationship_memories_memory_id"), table_name="relationship_memories")
    op.drop_table("relationship_memories")
    op.drop_index(op.f("ix_object_memories_owner_id"), table_name="object_memories")
    op.drop_index(op.f("ix_object_memories_name"), table_name="object_memories")
    op.drop_index(op.f("ix_object_memories_memory_id"), table_name="object_memories")
    op.drop_table("object_memories")
    op.drop_index(op.f("ix_memory_versions_memory_id"), table_name="memory_versions")
    op.drop_table("memory_versions")
    op.drop_index(op.f("ix_event_memories_name"), table_name="event_memories")
    op.drop_index(op.f("ix_event_memories_memory_id"), table_name="event_memories")
    op.drop_index(op.f("ix_event_memories_chapter_id"), table_name="event_memories")
    op.drop_table("event_memories")
    op.drop_index(op.f("ix_character_memories_name"), table_name="character_memories")
    op.drop_index(op.f("ix_character_memories_memory_id"), table_name="character_memories")
    op.drop_table("character_memories")
    op.drop_index(op.f("ix_ability_memories_owner_id"), table_name="ability_memories")
    op.drop_index(op.f("ix_ability_memories_name"), table_name="ability_memories")
    op.drop_index(op.f("ix_ability_memories_memory_id"), table_name="ability_memories")
    op.drop_table("ability_memories")
    op.drop_index(op.f("ix_retrieval_indices_keyword"), table_name="retrieval_indices")
    op.drop_index(op.f("ix_retrieval_indices_entity_id"), table_name="retrieval_indices")
    op.drop_table("retrieval_indices")
    op.drop_index(op.f("ix_memory_store_memory_type"), table_name="memory_store")
    op.drop_index(op.f("ix_memory_store_entity_type"), table_name="memory_store")
    op.drop_index(op.f("ix_memory_store_entity_id"), table_name="memory_store")
    op.drop_table("memory_store")
    op.drop_index(op.f("ix_memory_audits_entity_id"), table_name="memory_audits")
    op.drop_table("memory_audits")
    op.drop_index(op.f("ix_knowledge_graph_nodes_node_id"), table_name="knowledge_graph_nodes")
    op.drop_table("knowledge_graph_nodes")
    op.drop_index(op.f("ix_knowledge_graph_edges_target_node_id"), table_name="knowledge_graph_edges")
    op.drop_index(op.f("ix_knowledge_graph_edges_source_node_id"), table_name="knowledge_graph_edges")
    op.drop_table("knowledge_graph_edges")
    op.drop_index(op.f("ix_embeddings_entity_id"), table_name="embeddings")
    op.drop_table("embeddings")
    op.drop_index(op.f("ix_conflict_reports_entity_id"), table_name="conflict_reports")
    op.drop_table("conflict_reports")
    op.drop_table("confidence_scores")
    # ### end Alembic commands ###
