"""Add optimization models

Revision ID: de74753c6161
Revises: 31cf2b7737e6
Create Date: 2026-07-10 08:58:25.058763

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de74753c6161"
down_revision: Union[str, Sequence[str], None] = "31cf2b7737e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archive_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("archive_path", sa.String(length=1024), nullable=False),
        sa.Column("size_mb", sa.Float(), nullable=False),
        sa.Column("compression_ratio", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_archive_history_project_id"), "archive_history", ["project_id"], unique=False)
    op.create_table(
        "benchmarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("component", sa.String(length=100), nullable=False),
        sa.Column("operation", sa.String(length=100), nullable=False),
        sa.Column("execution_time", sa.Float(), nullable=False),
        sa.Column("memory_usage", sa.Float(), nullable=True),
        sa.Column("cpu_usage", sa.Float(), nullable=True),
        sa.Column("gpu_usage", sa.Float(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_benchmarks_component"), "benchmarks", ["component"], unique=False)
    op.create_index(op.f("ix_benchmarks_operation"), "benchmarks", ["operation"], unique=False)
    op.create_table(
        "cost_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=50), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("gpu_hours", sa.Float(), nullable=False),
        sa.Column("cpu_hours", sa.Float(), nullable=False),
        sa.Column("storage_gb", sa.Float(), nullable=False),
        sa.Column("api_costs", sa.Float(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cost_reports_period"), "cost_reports", ["period"], unique=False)
    op.create_table(
        "dependency_graph",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.String(length=100), nullable=False),
        sa.Column("dependencies", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("hash_state", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dependency_graph_node_id"), "dependency_graph", ["node_id"], unique=False)
    op.create_index(op.f("ix_dependency_graph_project_id"), "dependency_graph", ["project_id"], unique=False)
    op.create_table(
        "deployment_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_env", sa.String(length=100), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deployment_profiles_target_env"), "deployment_profiles", ["target_env"], unique=False)
    op.create_table(
        "inference_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cache_key", sa.String(length=255), nullable=False),
        sa.Column("component", sa.String(length=100), nullable=False),
        sa.Column("response_payload", sa.JSON(), nullable=False),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inference_cache_cache_key"), "inference_cache", ["cache_key"], unique=True)
    op.create_index(op.f("ix_inference_cache_component"), "inference_cache", ["component"], unique=False)
    op.create_index(op.f("ix_inference_cache_expires_at"), "inference_cache", ["expires_at"], unique=False)
    op.create_table(
        "model_benchmarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("accuracy", sa.Float(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("cost_per_1k", sa.Float(), nullable=True),
        sa.Column("vram_usage_mb", sa.Float(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_benchmarks_model_name"), "model_benchmarks", ["model_name"], unique=False)
    op.create_index(op.f("ix_model_benchmarks_provider"), "model_benchmarks", ["provider"], unique=False)
    op.create_table(
        "optimization_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("optimization_type", sa.String(length=100), nullable=False),
        sa.Column("original_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("rolled_back", sa.Boolean(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_optimization_history_optimization_type"), "optimization_history", ["optimization_type"], unique=False
    )
    op.create_index(op.f("ix_optimization_history_project_id"), "optimization_history", ["project_id"], unique=False)
    op.create_table(
        "performance_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("cpu_threads", sa.Integer(), nullable=False),
        sa.Column("gpu_workers", sa.Integer(), nullable=False),
        sa.Column("memory_limit_mb", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("config_overrides", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_performance_profiles_name"), "performance_profiles", ["name"], unique=True)
    op.create_table(
        "resource_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=100), nullable=False),
        sa.Column("cpu_usage_avg", sa.Float(), nullable=False),
        sa.Column("gpu_usage_avg", sa.Float(), nullable=True),
        sa.Column("memory_peak_mb", sa.Float(), nullable=False),
        sa.Column("disk_io_mb", sa.Float(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_resource_usage_job_id"), "resource_usage", ["job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_resource_usage_job_id"), table_name="resource_usage")
    op.drop_table("resource_usage")
    op.drop_index(op.f("ix_performance_profiles_name"), table_name="performance_profiles")
    op.drop_table("performance_profiles")
    op.drop_index(op.f("ix_optimization_history_project_id"), table_name="optimization_history")
    op.drop_index(op.f("ix_optimization_history_optimization_type"), table_name="optimization_history")
    op.drop_table("optimization_history")
    op.drop_index(op.f("ix_model_benchmarks_provider"), table_name="model_benchmarks")
    op.drop_index(op.f("ix_model_benchmarks_model_name"), table_name="model_benchmarks")
    op.drop_table("model_benchmarks")
    op.drop_index(op.f("ix_inference_cache_expires_at"), table_name="inference_cache")
    op.drop_index(op.f("ix_inference_cache_component"), table_name="inference_cache")
    op.drop_index(op.f("ix_inference_cache_cache_key"), table_name="inference_cache")
    op.drop_table("inference_cache")
    op.drop_index(op.f("ix_deployment_profiles_target_env"), table_name="deployment_profiles")
    op.drop_table("deployment_profiles")
    op.drop_index(op.f("ix_dependency_graph_project_id"), table_name="dependency_graph")
    op.drop_index(op.f("ix_dependency_graph_node_id"), table_name="dependency_graph")
    op.drop_table("dependency_graph")
    op.drop_index(op.f("ix_cost_reports_period"), table_name="cost_reports")
    op.drop_table("cost_reports")
    op.drop_index(op.f("ix_benchmarks_operation"), table_name="benchmarks")
    op.drop_index(op.f("ix_benchmarks_component"), table_name="benchmarks")
    op.drop_table("benchmarks")
    op.drop_index(op.f("ix_archive_history_project_id"), table_name="archive_history")
    op.drop_table("archive_history")
    # ### end Alembic commands ###
