"""Add voice models

Revision ID: e8c68d1fa1bc
Revises: db8b0d5e648e
Create Date: 2026-07-07 08:55:56.207857

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e8c68d1fa1bc'
down_revision: Union[str, Sequence[str], None] = 'db8b0d5e648e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('voice_id', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('accent', sa.String(length=50), nullable=True),
    sa.Column('is_cloned', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_profiles_name'), 'voice_profiles', ['name'], unique=False)
    op.create_table('audio_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('current_segment', sa.Integer(), nullable=True),
    sa.Column('total_segments', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_jobs_project_id'), 'audio_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_audio_jobs_status'), 'audio_jobs', ['status'], unique=False)
    op.create_table('pronunciation_dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('original_text', sa.String(length=255), nullable=False),
    sa.Column('phonetic_spelling', sa.String(length=255), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pronunciation_dictionary_original_text'), 'pronunciation_dictionary', ['original_text'], unique=False)
    op.create_index(op.f('ix_pronunciation_dictionary_project_id'), 'pronunciation_dictionary', ['project_id'], unique=False)
    op.create_table('audio_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.String(length=255), nullable=True),
    sa.Column('chapter_id', sa.String(length=255), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('voice_profile_id', sa.Integer(), nullable=True),
    sa.Column('emotion', sa.String(length=50), nullable=True),
    sa.Column('speech_rate', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['audio_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_profile_id'], ['voice_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_segments_chapter_id'), 'audio_segments', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_audio_segments_job_id'), 'audio_segments', ['job_id'], unique=False)
    op.create_index(op.f('ix_audio_segments_scene_id'), 'audio_segments', ['scene_id'], unique=False)
    op.create_index(op.f('ix_audio_segments_sequence_number'), 'audio_segments', ['sequence_number'], unique=False)
    op.create_table('audio_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['audio_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_versions_job_id'), 'audio_versions', ['job_id'], unique=False)
    op.create_table('audio_quality_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['audio_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['audio_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_quality_reports_job_id'), 'audio_quality_reports', ['job_id'], unique=False)
    op.create_table('timestamp_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['audio_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timestamp_index_segment_id'), 'timestamp_index', ['segment_id'], unique=False)
    op.drop_index(op.f('ix_ability_memories_memory_id'), table_name='ability_memories')
    op.create_index(op.f('ix_ability_memories_memory_id'), 'ability_memories', ['memory_id'], unique=True)
    op.drop_index(op.f('ix_character_memories_memory_id'), table_name='character_memories')
    op.create_index(op.f('ix_character_memories_memory_id'), 'character_memories', ['memory_id'], unique=True)
    op.drop_index(op.f('ix_event_memories_memory_id'), table_name='event_memories')
    op.create_index(op.f('ix_event_memories_memory_id'), 'event_memories', ['memory_id'], unique=True)
    op.drop_index(op.f('ix_object_memories_memory_id'), table_name='object_memories')
    op.create_index(op.f('ix_object_memories_memory_id'), 'object_memories', ['memory_id'], unique=True)
    op.drop_index(op.f('ix_relationship_memories_memory_id'), table_name='relationship_memories')
    op.create_index(op.f('ix_relationship_memories_memory_id'), 'relationship_memories', ['memory_id'], unique=True)
    op.drop_index(op.f('ix_world_memories_memory_id'), table_name='world_memories')
    op.create_index(op.f('ix_world_memories_memory_id'), 'world_memories', ['memory_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_world_memories_memory_id'), table_name='world_memories')
    op.create_index(op.f('ix_world_memories_memory_id'), 'world_memories', ['memory_id'], unique=False)
    op.drop_index(op.f('ix_relationship_memories_memory_id'), table_name='relationship_memories')
    op.create_index(op.f('ix_relationship_memories_memory_id'), 'relationship_memories', ['memory_id'], unique=False)
    op.drop_index(op.f('ix_object_memories_memory_id'), table_name='object_memories')
    op.create_index(op.f('ix_object_memories_memory_id'), 'object_memories', ['memory_id'], unique=False)
    op.drop_index(op.f('ix_event_memories_memory_id'), table_name='event_memories')
    op.create_index(op.f('ix_event_memories_memory_id'), 'event_memories', ['memory_id'], unique=False)
    op.drop_index(op.f('ix_character_memories_memory_id'), table_name='character_memories')
    op.create_index(op.f('ix_character_memories_memory_id'), 'character_memories', ['memory_id'], unique=False)
    op.drop_index(op.f('ix_ability_memories_memory_id'), table_name='ability_memories')
    op.create_index(op.f('ix_ability_memories_memory_id'), 'ability_memories', ['memory_id'], unique=False)
    op.drop_index(op.f('ix_timestamp_index_segment_id'), table_name='timestamp_index')
    op.drop_table('timestamp_index')
    op.drop_index(op.f('ix_audio_quality_reports_job_id'), table_name='audio_quality_reports')
    op.drop_table('audio_quality_reports')
    op.drop_index(op.f('ix_audio_versions_job_id'), table_name='audio_versions')
    op.drop_table('audio_versions')
    op.drop_index(op.f('ix_audio_segments_sequence_number'), table_name='audio_segments')
    op.drop_index(op.f('ix_audio_segments_scene_id'), table_name='audio_segments')
    op.drop_index(op.f('ix_audio_segments_job_id'), table_name='audio_segments')
    op.drop_index(op.f('ix_audio_segments_chapter_id'), table_name='audio_segments')
    op.drop_table('audio_segments')
    op.drop_index(op.f('ix_pronunciation_dictionary_project_id'), table_name='pronunciation_dictionary')
    op.drop_index(op.f('ix_pronunciation_dictionary_original_text'), table_name='pronunciation_dictionary')
    op.drop_table('pronunciation_dictionary')
    op.drop_index(op.f('ix_audio_jobs_status'), table_name='audio_jobs')
    op.drop_index(op.f('ix_audio_jobs_project_id'), table_name='audio_jobs')
    op.drop_table('audio_jobs')
    op.drop_index(op.f('ix_voice_profiles_name'), table_name='voice_profiles')
    op.drop_table('voice_profiles')
    # ### end Alembic commands ###
